import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect, useMemo, useState } from "react";
import { Controller, FormProvider, useForm, useFormContext, useWatch, type Path } from "react-hook-form";
import { createTemplateConfig, createTemplateFourFrames } from "@shared/lib/project-editor-defaults";
import { bespokeModules, browserFocalPositions, narrativeDepths, projectEditorInputSchema, type HorizontalFrame, type ProjectEditorInput } from "@shared/schemas/project-editor";
import { projectCategories, templateTypes, type TemplateType } from "@shared/schemas/project";
import type { ProjectEditorData } from "@shared/types/project-editor";
import { uploadImages, uploadSequence } from "@/lib/projects-api";
import { formatCategory, formatTemplate } from "@/lib/project-format";

type FieldPath = Path<ProjectEditorInput>;
const path = (value: string) => value as FieldPath;
const editorSections = ["General", "Browser", "Hero", "Theme", "Template Content", "Gallery", "Footer", "SEO"] as const;

function Field({ label, name, description, type = "text", required }: { label: string; name: string; description?: string; type?: string; required?: boolean }) {
  const { register, formState: { errors } } = useFormContext<ProjectEditorInput>();
  const fieldError = useMemo(() => {
    let node: unknown = errors;
    for (const key of name.split(".")) node = node && typeof node === "object" ? (node as Record<string, unknown>)[key] : undefined;
    return node && typeof node === "object" && "message" in node ? String((node as { message?: unknown }).message ?? "") : "";
  }, [errors, name]);
  return <div className="field-group"><label>{label}{required ? " *" : ""}</label><input type={type} aria-invalid={Boolean(fieldError)} {...register(path(name), type === "number" ? { valueAsNumber: true } : undefined)} />{description && <p className="field-hint">{description}</p>}{fieldError && <p className="field-error">{fieldError}</p>}</div>;
}

function TextArea({ label, name, description }: { label: string; name: string; description?: string }) {
  const { register } = useFormContext<ProjectEditorInput>();
  return <div className="field-group"><label>{label}</label><textarea rows={4} {...register(path(name))} />{description && <p className="field-hint">{description}</p>}</div>;
}

function Lines({ label, name, count }: { label: string; name: string; count?: number }) {
  const { control } = useFormContext<ProjectEditorInput>();
  return <Controller control={control} name={path(name)} render={({ field }) => <div className="field-group"><label>{label}</label><textarea rows={count ?? 3} value={Array.isArray(field.value) ? field.value.join("\n") : ""} onChange={(event) => field.onChange(event.target.value.split("\n").slice(0, count ?? 8))} /><p className="field-hint">One line per row{count ? ` · ${count} lines` : ""}</p></div>} />;
}

function SectionToggle({ label, name, children }: { label: string; name: string; children: React.ReactNode }) {
  const { register } = useFormContext<ProjectEditorInput>();
  const enabled = useWatch<ProjectEditorInput>({ name: path(name) }) as boolean;
  return <section className={`editor-subsection ${enabled ? "is-enabled" : ""}`}><header><div><p className="eyebrow">Template section</p><h3>{label}</h3></div><label className="toggle"><input type="checkbox" {...register(path(name))} /><span>{enabled ? "Enabled" : "Disabled"}</span></label></header><div className="editor-subsection-content">{children}</div></section>;
}

function MediaField({ label, base, optional = false }: { label: string; base: string; optional?: boolean }) {
  const { setValue } = useFormContext<ProjectEditorInput>();
  const media = useWatch<ProjectEditorInput>({ name: path(base) }) as { src?: string; alt?: string; focalPosition?: string } | undefined;
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  async function choose(files: FileList | null) {
    if (!files?.[0]) return;
    setBusy(true); setError("");
    try { const [saved] = await uploadImages([files[0]]); setValue(path(`${base}.src`), saved.url as never, { shouldDirty: true, shouldValidate: true }); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed"); }
    finally { setBusy(false); }
  }
  function remove() { setValue(path(base), optional ? undefined as never : { src: "", alt: "", focalPosition: "center" } as never, { shouldDirty: true, shouldValidate: true }); }
  return <div className="media-field"><div className="media-preview">{media?.src ? <img src={media.src} alt={media.alt ?? ""} /> : <span>No image</span>}</div><div className="media-fields"><div className="media-heading"><strong>{label}</strong><div><label className="upload-button">{busy ? "Uploading…" : media?.src ? "Replace" : "Upload"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event) => void choose(event.target.files)} /></label>{media?.src && <button type="button" className="quiet-button" onClick={remove}>Remove</button>}</div></div><Field label="Source" name={`${base}.src`} description="Uploaded media path; editable for an approved HTTP(S) source." /><Field label="Alt text" name={`${base}.alt`} /><Field label="Focal position" name={`${base}.focalPosition`} />{optional && <p className="field-hint">If empty, mobile uses the desktop image.</p>}{error && <p className="field-error">{error}</p>}</div></div>;
}

function ImageUrlField({ label, name, altName }: { label: string; name: string; altName?: string }) {
  const { setValue } = useFormContext<ProjectEditorInput>();
  const value = String(useWatch<ProjectEditorInput>({ name: path(name) }) ?? "");
  const [busy, setBusy] = useState(false);
  async function choose(files: FileList | null) { if (!files?.[0]) return; setBusy(true); try { const [saved] = await uploadImages([files[0]]); setValue(path(name), saved.url as never, { shouldDirty: true, shouldValidate: true }); } finally { setBusy(false); } }
  return <div className="media-field"><div className="media-preview">{value ? <img src={value} alt="" /> : <span>No image</span>}</div><div className="media-fields"><div className="media-heading"><strong>{label}</strong><div><label className="upload-button">{busy ? "Uploading…" : value ? "Replace" : "Upload"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event) => void choose(event.target.files)} /></label>{value && <button type="button" className="quiet-button" onClick={() => setValue(path(name), "" as never, { shouldDirty: true })}>Remove</button>}</div></div><Field label="Source" name={name} />{altName && <Field label="Alt text" name={altName} />}</div></div>;
}

function FocalSelect({ label, name }: { label: string; name: string }) {
  const { register } = useFormContext<ProjectEditorInput>();
  return <div className="field-group"><label>{label}</label><select {...register(path(name))}><option value="">Inherit / default</option>{browserFocalPositions.map((value) => <option key={value} value={value}>{value}</option>)}</select></div>;
}

function TemplateFourHorizontalStory({ base }: { base: string }) {
  const { setValue } = useFormContext<ProjectEditorInput>();
  const frames = (useWatch<ProjectEditorInput>({ name: path(`${base}.content.frames`) }) ?? []) as HorizontalFrame[];
  if (!frames.length) {
    return <div className="editor-note"><p>This project has no horizontal frames yet. Initialize the locked Template 4 sequence to edit its CMS-owned content.</p><button className="quiet-button" type="button" onClick={() => setValue(path(`${base}.content.frames`), createTemplateFourFrames() as never, { shouldDirty: true, shouldValidate: true })}>Initialize locked frames</button></div>;
  }
  return <div className="horizontal-frame-list">{frames.map((frame, index) => {
    const frameBase = `${base}.content.frames.${index}`;
    if (frame.type === "editorial") return <section className="frame-group" key={frame.id ?? `${frame.type}-${index}`}><header className="frame-heading"><div><p className="eyebrow">Frame {index + 1}</p><h4>Editorial</h4></div><span>Locked position</span></header><Lines label="Heading lines" name={`${frameBase}.headingLines`} /><TextArea label="Body" name={`${frameBase}.body`} /><div className="compact-grid"><Field label="Heading line 1" name={`${frameBase}.headingLine1`} /><Field label="Heading line 2A" name={`${frameBase}.headingLine2A`} /><Field label="Heading line 2B" name={`${frameBase}.headingLine2B`} /><Field label="Heading line 3" name={`${frameBase}.headingLine3`} /><Field label="Heading line 4A" name={`${frameBase}.headingLine4A`} /><Field label="Heading line 4B" name={`${frameBase}.headingLine4B`} /></div></section>;
    if (frame.type === "imageScene") return <section className="frame-group" key={frame.id ?? `${frame.type}-${index}`}><header className="frame-heading"><div><p className="eyebrow">Frame {index + 1}</p><h4>Image scene</h4></div><span>Locked position</span></header><div className="media-grid"><div><ImageUrlField label="Primary image" name={`${frameBase}.primaryImage`} altName={`${frameBase}.primaryImageAlt`} /><FocalSelect label="Primary focal position" name={`${frameBase}.primaryImageFocal`} /></div><div><ImageUrlField label="Secondary image — optional" name={`${frameBase}.secondaryImage`} altName={`${frameBase}.secondaryImageAlt`} /><FocalSelect label="Secondary focal position" name={`${frameBase}.secondaryImageFocal`} /></div></div></section>;
    if (frame.type === "editorialImage") return <section className="frame-group" key={frame.id ?? `${frame.type}-${index}`}><header className="frame-heading"><div><p className="eyebrow">Frame {index + 1}</p><h4>Editorial image</h4></div><span>Locked position</span></header><div className="compact-grid"><Field label="Heading line 1" name={`${frameBase}.headingLine1`} /><Field label="Heading line 2A" name={`${frameBase}.headingLine2A`} /><Field label="Heading line 2B" name={`${frameBase}.headingLine2B`} /><Field label="Heading line 3" name={`${frameBase}.headingLine3`} /><Field label="Heading line 4A" name={`${frameBase}.headingLine4A`} /><Field label="Heading line 4B" name={`${frameBase}.headingLine4B`} /></div><TextArea label="Body" name={`${frameBase}.body`} /><ImageUrlField label="Image" name={`${frameBase}.image`} altName={`${frameBase}.imageAlt`} /><FocalSelect label="Image focal position" name={`${frameBase}.imageFocal`} /></section>;
    return <section className="frame-group" key={frame.id ?? `${frame.type}-${index}`}><header className="frame-heading"><div><p className="eyebrow">Frame {index + 1}</p><h4>Intrinsic image</h4></div><span>Existing frame · locked position</span></header><ImageUrlField label="Image" name={`${frameBase}.src`} altName={`${frameBase}.alt`} /><div className="compact-grid"><FocalSelect label="Focal position" name={`${frameBase}.focalPosition`} /><Field label="Caption" name={`${frameBase}.caption`} /></div></section>;
  })}</div>;
}

function IntroFields({ base }: { base: string }) { return <><Lines label="Heading lines" name={`${base}.headingLines`} /><TextArea label="Body copy" name={`${base}.bodyCopy`} /></>; }
function HorizontalTwelve({ base }: { base: string }) { return <><Lines label="Frame 1 heading" name={`${base}.frame1Heading`} count={3} /><TextArea label="Frame 1 body" name={`${base}.frame1Body`} /><div className="media-grid"><MediaField label="Frame 2 primary" base={`${base}.frame2PrimaryMedia`} /><MediaField label="Frame 2 secondary" base={`${base}.frame2SecondaryMedia`} /><MediaField label="Frame 3 media" base={`${base}.frame3Media`} /></div><div className="compact-grid"><Field label="Frame 3 heading 1" name={`${base}.frame3Heading1`} /><Field label="Frame 3 heading 2A" name={`${base}.frame3Heading2A`} /><Field label="Frame 3 heading 2B" name={`${base}.frame3Heading2B`} /><Field label="Frame 3 heading 3" name={`${base}.frame3Heading3`} /><Field label="Frame 3 heading 4A" name={`${base}.frame3Heading4A`} /><Field label="Frame 3 heading 4B" name={`${base}.frame3Heading4B`} /></div><TextArea label="Frame 3 body" name={`${base}.frame3Body`} /></>; }
function DrawingTwelve({ base }: { base: string }) { return <><div className="compact-grid"><Field label="Area label" name={`${base}.drawingAreaLabel`} /><Field label="Title" name={`${base}.drawingTitle`} /><Field label="Accent color" name={`${base}.accentColor`} /></div><TextArea label="Description" name={`${base}.drawingDescription`} /><MediaField label="Drawing media" base={`${base}.media`} /></>; }

function Narrative({ base }: { base: string }) {
  const { register, setValue } = useFormContext<ProjectEditorInput>();
  const images = (useWatch<ProjectEditorInput>({ name: path(`${base}.images`) }) ?? []) as Array<{ id: string; src: string; alt: string; focalPosition?: string; depth: string; speed: number }>;
  async function add(files: FileList | null) { if (!files?.length) return; const uploaded = await uploadImages(Array.from(files)); const next = [...images, ...uploaded.map((file) => ({ id: crypto.randomUUID(), src: file.url, alt: "", focalPosition: "center", depth: "middle", speed: 1 }))]; setValue(path(`${base}.images`), next as never, { shouldDirty: true, shouldValidate: true }); }
  function remove(index: number) { const next = images.filter((_, itemIndex) => itemIndex !== index); setValue(path(`${base}.images`), next as never, { shouldDirty: true, shouldValidate: true }); }
  function move(index: number, offset: number) { const next = [...images]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setValue(path(`${base}.images`), next as never, { shouldDirty: true }); }
  return <><Lines label="Heading lines" name={`${base}.headingLines`} /><TextArea label="Body copy" name={`${base}.bodyCopy`} /><label className="upload-button">Upload narrative images<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => void add(event.target.files)} /></label><div className="collection-list">{images.map((image, index) => <article key={image.id} className="collection-item"><img src={image.src} alt="" /><div className="collection-fields"><Field label="Alt text" name={`${base}.images.${index}.alt`} /><Field label="Focal position" name={`${base}.images.${index}.focalPosition`} /><div className="compact-grid"><div className="field-group"><label>Depth</label><select {...register(path(`${base}.images.${index}.depth`))}>{narrativeDepths.map((depth) => <option key={depth}>{depth}</option>)}</select></div><Field label="Speed" name={`${base}.images.${index}.speed`} type="number" /></div></div><div className="collection-actions"><button type="button" onClick={() => move(index, -1)}>↑</button><button type="button" onClick={() => move(index, 1)}>↓</button><button type="button" onClick={() => remove(index)}>Remove</button></div></article>)}</div></>;
}

function TemplateContent({ template }: { template: TemplateType }) {
  const base = "templateConfig.sections";
  const { register } = useFormContext<ProjectEditorInput>();
  if (template === "template-1") return <><SectionToggle label="Statement" name={`${base}.statement.enabled`}><Lines label="Statement lines" name={`${base}.statement.lines`} /></SectionToggle><SectionToggle label="Story" name={`${base}.story.enabled`}><Lines label="Heading lines" name={`${base}.story.headingLines`} count={3} /><TextArea label="Body copy" name={`${base}.story.bodyCopy`} /><div className="media-grid"><MediaField label="Primary media" base={`${base}.story.primaryMedia`} /><MediaField label="Second media" base={`${base}.story.secondMedia`} /></div></SectionToggle><SectionToggle label="Bespoke" name={`${base}.bespoke.enabled`}><div className="field-group"><label>Frontend module</label><select {...register(path(`${base}.bespoke.module`))}>{bespokeModules.map((module) => <option key={module}>{module}</option>)}</select><p className="field-hint">Exploded-isometric compositions remain frontend-controlled; their layers and choreography are preserved outside this editor.</p></div></SectionToggle><SectionToggle label="Feature" name={`${base}.feature.enabled`}><Lines label="Heading lines" name={`${base}.feature.headingLines`} /><TextArea label="Body copy" name={`${base}.feature.bodyCopy`} /><MediaField label="Feature media" base={`${base}.feature.media`} /></SectionToggle><SectionToggle label="Horizontal Story" name={`${base}.horizontalStory.enabled`}><HorizontalTwelve base={`${base}.horizontalStory`} /></SectionToggle><SectionToggle label="Drawing" name={`${base}.drawing.enabled`}><Lines label="Heading lines" name={`${base}.drawing.headingLines`} /><TextArea label="Body copy" name={`${base}.drawing.bodyCopy`} /><Field label="Box color" name={`${base}.drawing.boxColor`} /><MediaField label="Drawing media" base={`${base}.drawing.media`} /></SectionToggle></>;
  if (template === "template-2") return <><SectionToggle label="Intro" name={`${base}.intro.enabled`}><IntroFields base={`${base}.intro`} /></SectionToggle><SectionToggle label="Horizontal Story" name={`${base}.horizontalStory.enabled`}><HorizontalTwelve base={`${base}.horizontalStory`} /></SectionToggle><SectionToggle label="Narrative" name={`${base}.narrative.enabled`}><Narrative base={`${base}.narrative`} /></SectionToggle><SectionToggle label="Drawing" name={`${base}.drawing.enabled`}><DrawingTwelve base={`${base}.drawing`} /></SectionToggle></>;
  if (template === "template-3") return <>
    <SectionToggle label="Intro" name={`${base}.intro.enabled`}><IntroFields base={`${base}.intro`} /></SectionToggle>
    <SequenceSection base={`${base}.bespoke`} />
    <SectionToggle label="Horizontal Story" name={`${base}.horizontalStory.enabled`}>
      <div className="compact-grid"><Field label="Accent color" name={`${base}.horizontalStory.accentColor`} /><Field label="Text color" name={`${base}.horizontalStory.textColor`} /></div>
      <div className="frame-group"><h4>Frame 1</h4><ImageUrlField label="Frame 1 image" name={`${base}.horizontalStory.frame1Image`} /></div>
      <div className="frame-group"><h4>Frame 2</h4><div className="compact-grid"><Field label="Heading line 1" name={`${base}.horizontalStory.frame2HeadingLine1`} /><Field label="Heading line 2A" name={`${base}.horizontalStory.frame2HeadingLine2A`} /><Field label="Heading line 2B" name={`${base}.horizontalStory.frame2HeadingLine2B`} /><Field label="Heading line 3" name={`${base}.horizontalStory.frame2HeadingLine3`} /><Field label="Heading line 4A" name={`${base}.horizontalStory.frame2Heading4A`} /><Field label="Heading line 4B" name={`${base}.horizontalStory.frame2Heading4B`} /></div><TextArea label="Body" name={`${base}.horizontalStory.frame2Body`} /><ImageUrlField label="Frame 2 image" name={`${base}.horizontalStory.frame2Image`} /></div>
      <div className="frame-group"><h4>Frame 3</h4><ImageUrlField label="Frame 3 image" name={`${base}.horizontalStory.frame3Image`} /></div>
      <div className="frame-group"><h4>Frame 4</h4><div className="compact-grid"><Field label="Heading line 1" name={`${base}.horizontalStory.frame4Heading1`} /><Field label="Heading line 2A" name={`${base}.horizontalStory.frame4Heading2A`} /><Field label="Heading line 2B" name={`${base}.horizontalStory.frame4Heading2B`} /><Field label="Heading line 3" name={`${base}.horizontalStory.frame4Heading3`} /><Field label="Heading line 4A" name={`${base}.horizontalStory.frame4Heading4A`} /><Field label="Heading line 4B" name={`${base}.horizontalStory.frame4Heading4B`} /></div><TextArea label="Body" name={`${base}.horizontalStory.frame4Body`} /><ImageUrlField label="Frame 4 image" name={`${base}.horizontalStory.frame4Image`} /></div>
    </SectionToggle>
    <SectionToggle label="Drawing" name={`${base}.drawing.enabled`}><Lines label="Heading lines" name={`${base}.drawing.headingLines`} /><TextArea label="Body copy" name={`${base}.drawing.bodyCopy`} /><div className="compact-grid"><Field label="Drawing alt" name={`${base}.drawing.drawingAlt`} /><Field label="Accent color" name={`${base}.drawing.accentColor`} /></div><ImageUrlField label="Drawing" name={`${base}.drawing.drawing`} altName={`${base}.drawing.drawingAlt`} /></SectionToggle>
  </>;
  return <><SectionToggle label="Intro" name={`${base}.intro.enabled`}><IntroFields base={`${base}.intro`} /></SectionToggle><SectionToggle label="Horizontal Story" name={`${base}.horizontalStory.enabled`}><p className="section-intro">Frame order, variants, and choreography are locked. Only content and media can be edited.</p><TemplateFourHorizontalStory base={`${base}.horizontalStory`} /></SectionToggle><SectionToggle label="Narrative" name={`${base}.narrative.enabled`}><Narrative base={`${base}.narrative`} /><MediaField label="Takeover image" base={`${base}.narrative.takeoverImage`} optional /></SectionToggle><SectionToggle label="Drawing" name={`${base}.drawing.enabled`}><DrawingTwelve base={`${base}.drawing`} /></SectionToggle></>;
}

function SequenceSection({ base }: { base: string }) {
  const { register, setValue } = useFormContext<ProjectEditorInput>();
  const frameCount = Number(useWatch<ProjectEditorInput>({ name: path(`${base}.frameCount`) }) ?? 0);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function upload(files: FileList | null) { if (!files?.length) return; setBusy(true); setMessage(""); try { const result = await uploadSequence(Array.from(files)); setValue(path(`${base}.framePath`), result.framePath as never, { shouldDirty: true }); setValue(path(`${base}.frameCount`), result.frameCount as never, { shouldDirty: true }); setMessage(`${result.frameCount} contiguous frames validated.`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Sequence upload failed"); } finally { setBusy(false); } }
  return <SectionToggle label="Bespoke / Scroll sequence" name={`${base}.enabled`}><div className="compact-grid"><div className="field-group"><label>Variant</label><select {...register(path(`${base}.variant`))}>{["editorial","fullscreen","option-1","option-2"].map((value) => <option key={value}>{value}</option>)}</select></div><label className="toggle"><input type="checkbox" {...register(path(`${base}.showEditorialIntro`))} /><span>Show editorial intro</span></label></div><label className="upload-button">{busy ? "Validating frames…" : "Upload numbered frames"}<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event) => void upload(event.target.files)} /></label><Field label="Sequence path" name={`${base}.framePath`} description="Generated from the validated upload." /><div className="derived-value"><span>Derived frame count</span><strong>{frameCount}</strong></div>{message && <p className="field-hint">{message}</p>}</SectionToggle>;
}

function GalleryEditor() {
  const { register, setValue } = useFormContext<ProjectEditorInput>();
  const images = (useWatch<ProjectEditorInput>({ name: "galleryConfig.images" }) ?? []) as Array<{ id: string; src: string; alt?: string; caption?: string; focalPosition?: string }>;
  const expanded = useWatch<ProjectEditorInput>({ name: "galleryConfig.expandedImages" }) as typeof images | undefined;
  async function add(files: FileList | null, expandedOnly = false) { if (!files?.length) return; const uploaded = await uploadImages(Array.from(files)); const additions = uploaded.map((file) => ({ id: crypto.randomUUID(), src: file.url, alt: "", caption: "", focalPosition: "center" })); if (expandedOnly) setValue("galleryConfig.expandedImages", [...(expanded ?? images), ...additions], { shouldDirty: true, shouldValidate: true }); else { const next = [...images, ...additions].slice(0, 9); setValue("galleryConfig.images", next, { shouldDirty: true, shouldValidate: true }); if (expanded) setValue("galleryConfig.expandedImages", [...expanded, ...additions], { shouldDirty: true, shouldValidate: true }); } }
  function update(next: typeof images) { setValue("galleryConfig.images", next, { shouldDirty: true, shouldValidate: true }); if (expanded) { const additions = next.filter((visible) => !expanded.some((item) => item.id === visible.id || item.src === visible.src)); setValue("galleryConfig.expandedImages", [...expanded, ...additions], { shouldDirty: true }); } }
  function move(index: number, offset: number) { const next = [...images]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; update(next); }
  function updateExpanded(next: typeof images) { setValue("galleryConfig.expandedImages", next, { shouldDirty: true, shouldValidate: true }); }
  function moveExpanded(index: number, offset: number) { if (!expanded) return; const next = [...expanded]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; updateExpanded(next); }
  return <>
    <label className="toggle"><input type="checkbox" {...register("galleryConfig.enabled")} /><span>Gallery enabled</span></label>
    <Lines label="Title lines" name="galleryConfig.titleLines" count={2} />
    <div className="collection-toolbar"><div><strong>Visible gallery images</strong><p>{images.length} selected · enabled galleries require 3, 6, or 9</p></div><label className="upload-button">Upload images<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => void add(event.target.files)} /></label></div>
    <div className="collection-list">{images.map((image, index) => <article key={image.id} className="collection-item"><img src={image.src} alt="" /><div className="collection-fields"><Field label="Alt text" name={`galleryConfig.images.${index}.alt`} /><Field label="Caption" name={`galleryConfig.images.${index}.caption`} /><Field label="Focal position" name={`galleryConfig.images.${index}.focalPosition`} /></div><div className="collection-actions"><button type="button" onClick={() => move(index,-1)}>↑</button><button type="button" onClick={() => move(index,1)}>↓</button><button type="button" onClick={() => update(images.filter((_, item) => item !== index))}>Remove</button></div></article>)}</div>
    <div className="expanded-control"><label className="toggle"><input type="checkbox" checked={Boolean(expanded)} onChange={(event) => setValue("galleryConfig.expandedImages", event.target.checked ? [...images] : undefined, { shouldDirty: true, shouldValidate: true })} /><span>Use a larger lightbox collection</span></label>{expanded && <><p className="field-hint">Visible images are kept in this collection automatically and cannot be removed here.</p><label className="upload-button">Add lightbox-only images<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => void add(event.target.files, true)} /></label><div className="collection-list">{expanded.map((image, index) => { const visible = images.some((item) => item.id === image.id || item.src === image.src); return <article key={image.id} className="collection-item"><img src={image.src} alt="" /><div className="collection-fields"><Field label="Alt text" name={`galleryConfig.expandedImages.${index}.alt`} /><Field label="Caption" name={`galleryConfig.expandedImages.${index}.caption`} /><Field label="Focal position" name={`galleryConfig.expandedImages.${index}.focalPosition`} /></div><div className="collection-actions"><button type="button" onClick={() => moveExpanded(index,-1)}>↑</button><button type="button" onClick={() => moveExpanded(index,1)}>↓</button><button type="button" disabled={visible} onClick={() => updateExpanded(expanded.filter((_, item) => item !== index))}>Remove</button></div></article>; })}</div></>}</div>
  </>;
}

export function ProjectEditorForm({ initial, onSave, saving, serverError }: { initial: ProjectEditorData; onSave: (input: ProjectEditorInput) => Promise<void>; saving: boolean; serverError?: string }) {
  const [active, setActive] = useState<(typeof editorSections)[number]>("General");
  const [saved, setSaved] = useState(false);
  const methods = useForm<ProjectEditorInput>({ resolver: zodResolver(projectEditorInputSchema), defaultValues: { general: initial.general, browserImage: initial.browserImage, hero: initial.hero, themeConfig: initial.themeConfig, templateConfig: initial.templateConfig, galleryConfig: initial.galleryConfig, footerConfig: initial.footerConfig, seoConfig: initial.seoConfig, confirmTemplateReset: false } });
  const { register, handleSubmit, reset, setValue, formState: { isDirty, errors } } = methods;
  const template = useWatch({ control: methods.control, name: "general.templateType" });
  useEffect(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (isDirty) event.preventDefault(); }; window.addEventListener("beforeunload", beforeUnload); return () => window.removeEventListener("beforeunload", beforeUnload); }, [isDirty]);
  async function submit(input: ProjectEditorInput) { setSaved(false); await onSave(input); reset({ ...input, confirmTemplateReset: false }); setSaved(true); window.setTimeout(() => setSaved(false), 2500); }
  function switchTemplate(next: TemplateType) { if (next === template) return; const needsWarning = initial.templateHasContent || methods.formState.dirtyFields.templateConfig; if (needsWarning && !window.confirm("Changing the template will reset all template-specific content. General, Browser, Hero, Theme, Gallery, Footer, and SEO will be preserved. Continue?")) return; setValue("general.templateType", next, { shouldDirty: true }); setValue("templateConfig", createTemplateConfig(next), { shouldDirty: true }); setValue("confirmTemplateReset", true, { shouldDirty: true }); }
  const firstError = Object.keys(errors)[0];
  return <FormProvider {...methods}><form className="editor-layout" onSubmit={handleSubmit(submit)} noValidate><aside className="editor-nav">{editorSections.map((section) => <button type="button" className={active === section ? "is-current" : ""} key={section} onClick={() => setActive(section)}>{section}</button>)}</aside><div className="editor-workspace"><div className="editor-savebar"><div>{isDirty ? <span className="dirty-status">Unsaved changes</span> : <span className="saved-status">{saved ? "Saved" : "All changes saved"}</span>}</div><button className="primary-button" type="submit" disabled={saving || !isDirty}>{saving ? "Saving…" : "Save project"}</button></div>{serverError && <p className="form-error" role="alert">{serverError}</p>}{firstError && <p className="form-error" role="alert">Review the {firstError === "templateConfig" ? "Template Content" : firstError} section.</p>}
  <section className="editor-panel" hidden={active !== "General"}><p className="eyebrow">General</p><h2>Project identity</h2><div className="compact-grid"><Field label="Project name" name="general.title" required /><Field label="Slug" name="general.slug" required /><div className="field-group"><label>Built / Unbuilt</label><select {...register("general.category")}>{projectCategories.map((value) => <option key={value} value={value}>{formatCategory(value)}</option>)}</select></div><div className="field-group"><label>Template</label><select value={template} onChange={(event) => switchTemplate(event.target.value as TemplateType)}>{templateTypes.map((value) => <option key={value} value={value}>{formatTemplate(value)}</option>)}</select></div><Field label="Location" name="general.location" /><Field label="Area" name="general.area" /><Field label="Year" name="general.year" /><Field label="Browser order" name="general.browserOrder" type="number" /></div></section>
  <section className="editor-panel" hidden={active !== "Browser"}><p className="eyebrow">Browser</p><h2>Project listing</h2><p className="section-intro">Independent media used by the public project browser.</p><MediaField label="Browser image" base="browserImage" /><div className="field-group"><label>Listing focal position</label><select {...register("browserImage.focalPosition")}>{browserFocalPositions.map((value) => <option key={value}>{value}</option>)}</select></div></section>
  <section className="editor-panel" hidden={active !== "Hero"}><p className="eyebrow">Hero</p><h2>Opening media</h2><label className="toggle"><input type="checkbox" {...register("hero.enabled")} /><span>Hero enabled</span></label><div className="media-grid"><MediaField label="Desktop image" base="hero.media" /><MediaField label="Mobile image — optional" base="hero.media.mobile" optional /></div><Lines label="Hero title" name="hero.title" count={2} /><div className="compact-grid"><Field label="Square footage" name="hero.squareFootage" /><Field label="Square footage label" name="hero.squareFootageLabel" /></div></section>
  <section className="editor-panel" hidden={active !== "Theme"}><p className="eyebrow">Theme</p><h2>Project colors</h2><div className="color-grid"><ColorField label="Project accent / background" name="themeConfig.horizontalBackgroundColor" /><ColorField label="Project text / foreground" name="themeConfig.horizontalTextColor" /></div></section>
  <section className="editor-panel" hidden={active !== "Template Content"}><p className="eyebrow">{formatTemplate(template)}</p><h2>Template content</h2><p className="section-intro">Section order and animation behavior remain owned by the frontend.</p><TemplateContent template={template} /></section>
  <section className="editor-panel" hidden={active !== "Gallery"}><p className="eyebrow">Gallery</p><h2>Project gallery</h2><GalleryEditor /></section>
  <section className="editor-panel" hidden={active !== "Footer"}><p className="eyebrow">Footer</p><h2>Project footer style</h2><input type="hidden" {...register("footerConfig.variant")} /><div className="choice-row three-up">{(["accent","black","white"] as const).map((value) => <label className="choice-option" key={value}><input type="radio" value={value} {...register("footerConfig.theme")} /><span>{value[0].toUpperCase()+value.slice(1)}</span></label>)}</div></section>
  <section className="editor-panel" hidden={active !== "SEO"}><p className="eyebrow">SEO</p><h2>Search and sharing</h2><Field label="SEO title" name="seoConfig.title" /><TextArea label="Meta description" name="seoConfig.description" /><ImageUrlField label="Social image — optional" name="seoConfig.socialImage" /></section>
  </div></form></FormProvider>;
}

function ColorField({ label, name }: { label: string; name: string }) {
  const { setValue, watch } = useFormContext<ProjectEditorInput>();
  const value = String(watch(path(name)) ?? "");
  const picker = /^#[0-9a-f]{6}$/i.test(value) ? value : "#000000";
  return <div className="color-field"><input type="color" value={picker} onChange={(event) => setValue(path(name), event.target.value as never, { shouldDirty: true, shouldValidate: true })} /><Field label={label} name={name} /></div>;
}
